import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { curatedRecordsOf, dimsOf, displaySvgOf, type RawTagRecord } from "@/lib/dialogue/galleryExport";

// dialogue mode — ייצוא נכסי הגלריה (‏PROMPT_SPEC §3.2). רץ אחרי כל שינוי
// אוצרות ב-`gallery-tags.json`, ומפיק את שני הדברים שהגלריה של הראיון צורכת:
//
//  1. `src/data/gallery-curated.json` — תקציר הרשימה המאוצרת (רק מה שהשיחה
//     צריכה; הקובץ המלא הוא 288KB ואינו נכנס לבאנדל של לקוחה). נכתב תמיד —
//     אין צורך ב-DB.
//  2. `public/gallery/<version_id>.svg` — קובץ תצוגה קטן לכל עיצוב מאוצר,
//     בקוטביות הנכונה (חומר מלא, חורים שקופים). דורש את ה-SVG הקנוני
//     מ-`design_versions`, ולכן רץ רק כשיש הרשאות DB — בפועל: ב-workflow
//     ‏`gallery-export.yml`, שם הסודות חיים (אותו נימוק כמו `story-lab.yml`).
//
// **הייצוא הוא חלק מ-PR האוצרות** (הכרעת גל, 22.8): קובץ בגיט הוא מקור האמת —
// גרסאות, diff וביקורת על כל שינוי — והגלריה אינה תלויה ב-DB בזמן ריצה:
// מחיקת גרסה מה-DB אינה שוברת גלריה שכבר יוצאה.
//
// הרצה: `npm run gallery:export` (מקומית בלי סודות — תקציר בלבד; ב-runner —
// הכול). כשל על עיצוב מאוצר אחד מפיל את הריצה בקול: גלריה עם חור היא
// גלריה שבורה, וריצה ירוקה שלא ייצאה כלום גרועה מריצה אדומה.

// הסקריפט רץ תמיד מ-`npm run gallery:export`, כלומר משורש הריפו — וזה גם מה
// שמחזיק אחרי הבאנדל: `import.meta.url` היה מצביע על `scripts/dist/`.
const root = process.cwd();
const FULL_PATH = join(root, "src/data/gallery-tags.json");
const CURATED_PATH = join(root, "src/data/gallery-curated.json");
const SVG_DIR = join(root, "public/gallery");

/** כמה גרסאות נשלפות בבקשה אחת. ‏SVG עקיב יכול להגיע ל-190KB — עשר לבקשה
 *  שומרות את התשובה בגודל שפוי. */
const FETCH_BATCH = 10;

async function main(): Promise<void> {
  const full = JSON.parse(readFileSync(FULL_PATH, "utf8")) as { designs?: RawTagRecord[] };
  const curated = curatedRecordsOf(full);
  if (!curated.length) {
    console.error("No curated records (overrides.gallery: true) in gallery-tags.json — nothing to export.");
    process.exit(1);
  }

  writeFileSync(
    CURATED_PATH,
    `${JSON.stringify(
      {
        schema_version: 1,
        source: "generated by scripts/export-gallery.ts from gallery-tags.json — do not edit by hand",
        designs: curated,
      },
      null,
      1,
    )}\n`,
  );
  console.log(`gallery-curated.json: ${curated.length} designs`);

  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SECRET_KEY;
  if (!url || !key) {
    console.log("SUPABASE_URL / SUPABASE_SECRET_KEY not set — skipped the SVG export (run via gallery-export.yml).");
    return;
  }

  // המידות לכל רשומה — נפילה-לאחור בלבד; המסגרת האמיתית נקראת מה-viewBox.
  const rawById = new Map<string, RawTagRecord>();
  for (const r of full.designs ?? []) {
    if (typeof r?.version_id === "string") rawById.set(r.version_id, r);
  }

  const sb = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  mkdirSync(SVG_DIR, { recursive: true });

  const failures: string[] = [];
  let written = 0;
  for (let at = 0; at < curated.length; at += FETCH_BATCH) {
    const batch = curated.slice(at, at + FETCH_BATCH);
    const { data, error } = await sb
      .from("design_versions")
      .select("id, svg")
      .in("id", batch.map((d) => d.version_id));
    if (error) {
      console.error(`fetch failed at batch ${at / FETCH_BATCH + 1}: ${error.message}`);
      process.exit(1);
    }
    const svgById = new Map(
      ((data ?? []) as Array<{ id: string; svg: string | null }>).map((r) => [r.id, r.svg]),
    );
    for (const d of batch) {
      const svg = svgById.get(d.version_id);
      if (!svg) {
        failures.push(`${d.version_id}: version missing from design_versions`);
        continue;
      }
      const display = displaySvgOf(svg, dimsOf(rawById.get(d.version_id) ?? {}));
      if (!display) {
        failures.push(`${d.version_id}: svg breaks the preview contract`);
        continue;
      }
      writeFileSync(join(SVG_DIR, `${d.version_id}.svg`), `${display}\n`);
      written += 1;
    }
  }

  // קבצים של עיצובים שיצאו מהרשימה המאוצרת אינם נשארים מאחור — הייצוא הוא
  // מקור האמת של התיקייה כולה.
  const keep = new Set(curated.map((d) => `${d.version_id}.svg`));
  let removed = 0;
  if (existsSync(SVG_DIR)) {
    for (const file of readdirSync(SVG_DIR)) {
      if (file.endsWith(".svg") && !keep.has(file)) {
        unlinkSync(join(SVG_DIR, file));
        removed += 1;
      }
    }
  }

  console.log(`public/gallery: ${written} written, ${removed} stale removed`);
  if (failures.length) {
    for (const f of failures) console.error(`FAILED ${f}`);
    console.error(`${failures.length} curated designs have no display svg — the gallery would show holes.`);
    process.exit(1);
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : String(e));
  process.exit(1);
});
