-- רישום משתמשים + מספר סידורי לעיצוב.
--
-- שתי החלטות שכדאי שיהיו כתובות:
--
-- 1) המשתמשים נכנסים ל-`profiles` הקיימת ולא לטבלה חדשה. `designs.profile_id`
--    כבר מצביע לשם, וכך כל מה שנבנה סביבו — מכסת היצירה היומית לפי פרופיל,
--    שליפת העיצובים של פרופיל, ה-FK — עובד למשתמש רשום בלי שינוי. טבלה שנייה
--    הייתה מחייבת עמודת בעלות שנייה ב-designs, ושתי דרכים לשאול "של מי זה".
--    `kind` מפריד בין ששת הבודקים של הסטודיו לבין מי שנרשם באתר.
--
-- 2) המספר הסידורי הוא עמודה במסד ולא נגזרת של ה-uuid. הוא הרפרנס שגל וחברים
--    יאמרו בקול ("מה עם RM-0007?") — הוא חייב להיות קצר, רץ, ויציב לנצח.
--    ה-backfill רץ לפי created_at כדי שמספר נמוך יהיה עיצוב ותיק יותר.

-- ===== משתמשים =====

alter table profiles add column if not exists kind text not null default 'tester';
alter table profiles add column if not exists email text;
alter table profiles add column if not exists phone text;
alter table profiles add column if not exists created_at timestamptz not null default now();
alter table profiles add column if not exists last_seen_at timestamptz not null default now();

do $$
begin
  alter table profiles add constraint profiles_kind_check check (kind in ('tester', 'friend'));
exception
  when duplicate_object then null;
end $$;

-- זיהוי חוזר לפי מייל. חלקי (where email is not null) כדי שששת הבודקים,
-- שאין להם מייל, לא יתנגשו זה בזה על NULL.
create unique index if not exists idx_profiles_email
  on profiles (lower(email))
  where email is not null;

create index if not exists idx_profiles_kind on profiles (kind);

-- ===== מספר סידורי לעיצוב =====

alter table designs add column if not exists serial bigint;

-- מילוי הקיימים לפי סדר יצירה. id כשובר שוויון — created_at הוא ברירת מחדל
-- ברמת השנייה ועשוי לחזור על עצמו.
with ordered as (
  select id, row_number() over (order by created_at, id) as rn
  from designs
  where serial is null
)
update designs d
set serial = o.rn
from ordered o
where d.id = o.id;

-- הפיכה ל-identity שממשיכה מאיפה שה-backfill נעצר. בתוך do $$ כי צריך
-- לחשב את start ולוודא אידמפוטנטיות (identity שכבר הוגדר זורק).
do $$
declare
  next_val bigint;
  has_identity boolean;
begin
  select exists (
    select 1
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'designs'
      and a.attname = 'serial' and a.attidentity <> ''
  ) into has_identity;

  if not has_identity then
    select coalesce(max(serial), 0) + 1 into next_val from designs;
    alter table designs alter column serial set not null;
    execute format(
      'alter table designs alter column serial add generated by default as identity (start with %s)',
      next_val
    );
  end if;
end $$;

create unique index if not exists idx_designs_serial on designs (serial);

-- PostgREST עונה מתוך schema cache. בלי הרענון הזה `serial` ו-`kind` קיימים
-- ב-Postgres וה-API עדיין מחזיר "Could not find ... in the schema cache" —
-- בדיוק מה שקרה אחרי 0004/0005 והצריך את 0006.
notify pgrst, 'reload schema';
